"""GridSpec + SolventModel -> an mg-auto input file.

One template, deliberately: mg-auto, lpbe, bcfl sdh, chgm spl4. The FEM,
geoflow, BEM, PBAM and PBSAM paths are out of scope, so none of their knobs
appear here.

Energy needs two elec blocks. A single block reports total electrostatic
energy, which is dominated by the self-energy of the point charges and is not
what anyone means by solvation energy; the polar solvation energy is the
difference between the solvated state and a uniform-dielectric reference with
no mobile ions. That difference is what APBS prints as `Global net ELEC
energy`, which is what run.py parses.
"""

from __future__ import annotations

from sashimi.apbs.grid import ApbsGrid
from sashimi.protocol import SolventModel

__all__ = ["POTENTIAL_STEM", "build_input"]

POTENTIAL_STEM = "potential"  # APBS appends .dx


def _elec_block(
    name: str,
    grid: ApbsGrid,
    solvent: SolventModel,
    *,
    sdie: float,
    ionic_strength: float,
    calcenergy: bool,
    write_potential: bool,
) -> str:
    nx, ny, nz = grid.dime
    cx, cy, cz = grid.cglen
    fx, fy, fz = grid.fglen

    lines = [
        f"elec name {name}",
        "    mg-auto",
        f"    dime {nx} {ny} {nz}",
        f"    cglen {cx:.4f} {cy:.4f} {cz:.4f}",
        f"    fglen {fx:.4f} {fy:.4f} {fz:.4f}",
        "    cgcent mol 1",
        "    fgcent mol 1",
        "    mol 1",
        "    lpbe",
        "    bcfl sdh",
        f"    pdie {solvent.solute_dielectric:.4f}",
        f"    sdie {sdie:.4f}",
        "    chgm spl4",
        f"    srfm {solvent.surface_method}",
        f"    srad {solvent.surface_radius:.4f}",
        "    swin 0.3",
        "    sdens 10.0",
        f"    temp {solvent.temperature:.4f}",
    ]
    if ionic_strength > 0:
        # 1:1 salt, symmetric.
        lines.append(f"    ion charge  1 conc {ionic_strength:.6f} radius {solvent.ion_radius:.4f}")
        lines.append(f"    ion charge -1 conc {ionic_strength:.6f} radius {solvent.ion_radius:.4f}")
    lines.append(f"    calcenergy {'total' if calcenergy else 'no'}")
    lines.append("    calcforce no")
    if write_potential:
        lines.append(f"    write pot dx {POTENTIAL_STEM}")
    lines.append("end")
    return "\n".join(lines)


def build_input(
    grid: ApbsGrid,
    solvent: SolventModel,
    *,
    pqr_filename: str = "mol.pqr",
    compute_energy: bool = False,
) -> str:
    blocks = [
        "# Generated by sashimi. Do not edit; regenerate from GridSpec/SolventModel.",
        "read",
        f"    mol pqr {pqr_filename}",
        "end",
        "",
        _elec_block(
            "solvated",
            grid,
            solvent,
            sdie=solvent.solvent_dielectric,
            ionic_strength=solvent.ionic_strength,
            calcenergy=compute_energy,
            write_potential=True,
        ),
    ]

    if compute_energy:
        # Reference state: uniform dielectric, no mobile ions, same grid.
        blocks += [
            "",
            _elec_block(
                "reference",
                grid,
                solvent,
                sdie=solvent.solute_dielectric,
                ionic_strength=0.0,
                calcenergy=True,
                write_potential=False,
            ),
            "",
            "print elecEnergy solvated - reference end",
        ]

    blocks += ["", "quit", ""]
    return "\n".join(blocks)
