"""FiniteDifferenceRequest -> an mg-auto input file.

One template, deliberately: mg-auto with the requested equation, `bcfl sdh`,
`chgm spl4`. The FEM, geoflow, BEM, PBAM and PBSAM paths are out of scope, so
none of their knobs appear here.

Energy needs two elec blocks. A single block reports total electrostatic
energy, which is dominated by the self-energy of the point charges and is not
what anyone means by solvation energy; the polar solvation energy is the
difference between the solvated state and a uniform-dielectric reference with
no mobile ions. That difference is what APBS prints as `Global net ELEC
energy`, which is what run.py parses.
"""

from __future__ import annotations

from sashimi.apbs.grid import ApbsGrid
from sashimi.apbs.options import EQUATION_KEYWORD, ApbsOptions, resolve_surface
from sashimi.protocol import Diagnostics, Equation, SolventModel

__all__ = ["POTENTIAL_STEM", "build_input", "resolved_parameters"]

POTENTIAL_STEM = "potential"  # APBS appends .dx


def _elec_block(
    name: str,
    grid: ApbsGrid,
    solvent: SolventModel,
    options: ApbsOptions,
    *,
    equation: Equation,
    sdie: float,
    ionic_strength: float,
    calcenergy: bool,
    write_potential: bool,
) -> str:
    nx, ny, nz = grid.dime
    cx, cy, cz = grid.cglen
    fx, fy, fz = grid.fglen
    srfm, srad = resolve_surface(solvent.surface_model, solvent.surface_radius, options)

    lines = [
        f"elec name {name}",
        "    mg-auto",
        f"    dime {nx} {ny} {nz}",
        f"    cglen {cx:.4f} {cy:.4f} {cz:.4f}",
        f"    fglen {fx:.4f} {fy:.4f} {fz:.4f}",
        "    cgcent mol 1",
        "    fgcent mol 1",
        "    mol 1",
        f"    {EQUATION_KEYWORD[equation]}",
        f"    bcfl {options.boundary_condition}",
        f"    pdie {solvent.solute_dielectric:.4f}",
        f"    sdie {sdie:.4f}",
        f"    chgm {options.charge_discretization}",
        f"    srfm {srfm}",
        f"    srad {srad:.4f}",
        f"    swin {options.spline_window:.4f}",
        f"    sdens {options.surface_density:.4f}",
        f"    temp {solvent.temperature:.4f}",
    ]
    if ionic_strength > 0:
        # 1:1 salt, symmetric.
        lines.append(f"    ion charge  1 conc {ionic_strength:.6f} radius {solvent.ion_radius:.4f}")
        lines.append(f"    ion charge -1 conc {ionic_strength:.6f} radius {solvent.ion_radius:.4f}")
    lines.append(f"    calcenergy {'total' if calcenergy else 'no'}")
    lines.append("    calcforce no")
    if write_potential:
        lines.append(f"    write pot dx {POTENTIAL_STEM}")
    lines.append("end")
    return "\n".join(lines)


def build_input(
    grid: ApbsGrid,
    solvent: SolventModel,
    options: ApbsOptions = ApbsOptions(),  # noqa: B008 — frozen dataclass
    *,
    equation: Equation = Equation.LINEAR,
    pqr_filename: str = "mol.pqr",
    compute_energy: bool = False,
    write_potential: bool = True,
) -> str:
    blocks = [
        "# Generated by sashimi. Do not edit; regenerate from the request.",
        "read",
        f"    mol pqr {pqr_filename}",
        "end",
        "",
        _elec_block(
            "solvated",
            grid,
            solvent,
            options,
            equation=equation,
            sdie=solvent.solvent_dielectric,
            ionic_strength=solvent.ionic_strength,
            calcenergy=compute_energy,
            write_potential=write_potential,
        ),
    ]

    if compute_energy:
        # Reference state: uniform dielectric, no mobile ions, same grid.
        blocks += [
            "",
            _elec_block(
                "reference",
                grid,
                solvent,
                options,
                equation=equation,
                sdie=solvent.solute_dielectric,
                ionic_strength=0.0,
                calcenergy=True,
                write_potential=False,
            ),
            "",
            "print elecEnergy solvated - reference end",
        ]

    blocks += ["", "quit", ""]
    return "\n".join(blocks)


def resolved_parameters(
    grid: ApbsGrid, solvent: SolventModel, options: ApbsOptions, *, equation: Equation
) -> Diagnostics:
    """What the backend actually used, for `Provenance.resolved_parameters`.

    Deliberately records the *mapped* values — `srfm`, `srad` and the equation
    keyword as APBS received them — alongside the portable ones, because that is
    what makes a surface-model mapping auditable after the fact and is what
    cross-solver comparison checks before reporting a spread.
    """
    srfm, srad = resolve_surface(solvent.surface_model, solvent.surface_radius, options)
    return {
        "equation": equation.value,
        "surface_model": solvent.surface_model.value,
        "solvent_dielectric": solvent.solvent_dielectric,
        "solute_dielectric": solvent.solute_dielectric,
        "ionic_strength": solvent.ionic_strength,
        "ion_radius": solvent.ion_radius,
        "temperature": solvent.temperature,
        "surface_radius": solvent.surface_radius,
        "apbs": {
            "equation_keyword": EQUATION_KEYWORD[equation],
            "srfm": srfm,
            "srad": srad,
            "swin": options.spline_window,
            "chgm": options.charge_discretization,
            "bcfl": options.boundary_condition,
            "sdens": options.surface_density,
            **grid.as_diagnostics(),
        },
    }
