"""FiniteDifferenceRequest -> a DelPhi parameter file.

Both flavours read the same statement syntax and the same short parameter
names, so this is one generator with a `DelphiFlavour` switch rather than two.
They genuinely differ in four places, and every one of them is a silent wrong
answer rather than an error if it is got wrong:

1. **Temperature units.** The C++ program's `temper` statement is in **degrees
   Celsius** — its parser ends `fTemper -= dAbsoluteZero` — while pyDelPhi's is
   in kelvin. Measured on a Born ion: writing `temper=298.15` to the C++ build
   runs the solve at 571.3 K and reports -48.13 kT where the correct answer is
   -92.22. Neither program complains, because 571 K is a legal temperature.
2. **Boundary condition.** The C++ program takes an integer code, pyDelPhi a
   name.
3. **Surface selection.** pyDelPhi names a `surfmethod`; the C++ program infers
   the surface from the probe radius and a Gaussian flag. See
   `sashimi.delphi.options` for the full mapping table.
4. **Energies.** The C++ program prints them only when asked with `energy(s,c)`;
   pyDelPhi always computes them and writes a CSV.

The structure statement is `in(modpdb4, ..., format=pqr)` and not
`in(pdb, ..., format=pqr)`. That is not a stylistic choice: DelPhi's `pqr`
reader takes the radius from columns 62-68 and its `pqr4` reader from 63-69,
and pdb2pqr — like sashimi's own writer — emits the latter layout. Read as
`pqr`, an ALA-GLY radius of 1.824 A parses as 4.0 A and the solve silently
proceeds on a structure made of wrong-sized atoms. `tests/test_delphi_input.py`
pins the column arithmetic.
"""

from __future__ import annotations

from sashimi.delphi.discover import DelphiFlavour
from sashimi.delphi.grid import DelphiGrid
from sashimi.delphi.options import DelphiOptions, resolve_surface
from sashimi.protocol import Diagnostics, Equation, SolventModel

__all__ = [
    "ABSOLUTE_ZERO_C",
    "POTENTIAL_FILENAME",
    "PQR_FILENAME",
    "build_input",
    "resolved_parameters",
]

PQR_FILENAME = "mol.pqr"
POTENTIAL_FILENAME = "potential.cube"

ABSOLUTE_ZERO_C = 273.15  # K; the offset the C++ `temper` statement applies

# DelPhi's boundary-condition codes. 4 is the full Coulombic sum over every
# charge, the closest available analogue to the Debye-Huckel boundary sashimi
# asks APBS for; it travels in provenance either way.
_CPP_BOUNDARY_CODE = 4
_PY_BOUNDARY_NAME = "coulombic"


def _temperature_value(temperature: float, flavour: DelphiFlavour) -> float:
    """The number to write after `temper=` for this flavour. See point 1 above."""
    if flavour is DelphiFlavour.CPP:
        return temperature - ABSOLUTE_ZERO_C
    return temperature


def build_input(
    grid: DelphiGrid,
    solvent: SolventModel,
    options: DelphiOptions = DelphiOptions(),  # noqa: B008 — frozen dataclass
    *,
    flavour: DelphiFlavour,
    pqr_filename: str = PQR_FILENAME,
    potential_filename: str = POTENTIAL_FILENAME,
    compute_energy: bool = True,
    write_potential: bool = True,
) -> str:
    surface = resolve_surface(solvent.surface_model, solvent.surface_radius, flavour)
    cx, cy, cz = grid.center

    lines = ["! Generated by sashimi. Do not edit; regenerate from the request."]

    if flavour is DelphiFlavour.PYDELPHI:
        # `pbe` is the linear equation; sashimi refuses the nonlinear one
        # upstream in `options.check_equation`, so no branch is needed here.
        lines += [
            "biomodel           = pbe",
            "solver             = sor",
            "gridbox_type       = cubic",
            f"surfacemethod      = {surface.keyword}",
            f"dielectricmodel    = {'gaussian' if surface.gaussian else 'twodielectric'}",
        ]

    lines += [
        f"gsize              = {grid.gsize}",
        f"scale              = {grid.scale:.8f}",
    ]

    if flavour is DelphiFlavour.CPP:
        # pyDelPhi has no `acent`; it centres the box on the solute itself.
        lines.append(f"acent({cx:.4f},{cy:.4f},{cz:.4f})")

    lines += [
        f"indi               = {solvent.solute_dielectric:.6f}",
        f"exdi               = {solvent.solvent_dielectric:.6f}",
        f"prbrad             = {surface.probe_radius:.4f}",
        f"salt               = {solvent.ionic_strength:.6f}",
        f"ionrad             = {solvent.ion_radius:.4f}",
        f"temper             = {_temperature_value(solvent.temperature, flavour):.6f}",
        f"linit              = {options.linear_iterations}",
        f"maxc               = {options.max_delta_phi:.8f}",
    ]

    if flavour is DelphiFlavour.CPP:
        lines.append(f"bndcon             = {_CPP_BOUNDARY_CODE}")
        if surface.gaussian:
            lines += [
                "gaussian           = 1",
                f"sigma              = {options.gaussian_sigma:.4f}",
                f"srfcut             = {options.gaussian_cutoff:.4f}",
            ]
    else:
        lines.append(f"bndcon             = {_PY_BOUNDARY_NAME}")
        if surface.gaussian:
            lines.append(f"gaussiansigma      = {options.gaussian_sigma:.4f}")

    if options.relaxation is not None:
        lines.append(f"relpar             = {options.relaxation:.6f}")

    lines.append(f'in(modpdb4,file="{pqr_filename}",format=pqr)')

    if compute_energy and flavour is DelphiFlavour.CPP:
        # pyDelPhi computes these unconditionally and writes them to CSV.
        lines.append("energy(s,c)")

    if write_potential:
        lines.append(f'out(phi,file="{potential_filename}",media="water",format=cube)')

    return "\n".join(lines) + "\n"


def resolved_parameters(
    grid: DelphiGrid,
    solvent: SolventModel,
    options: DelphiOptions,
    *,
    flavour: DelphiFlavour,
    equation: Equation,
) -> Diagnostics:
    """What the backend actually used, for `Provenance.resolved_parameters`.

    Records the mapped values — the probe radius the surface model became, the
    temperature as the file expresses it, and the units that reading was in —
    because a cross-solver comparison checks these before reporting a spread,
    and "298.15 in an input file" means two different temperatures here.
    """
    surface = resolve_surface(solvent.surface_model, solvent.surface_radius, flavour)
    temper = _temperature_value(solvent.temperature, flavour)
    return {
        "equation": equation.value,
        "surface_model": solvent.surface_model.value,
        "solvent_dielectric": solvent.solvent_dielectric,
        "solute_dielectric": solvent.solute_dielectric,
        "ionic_strength": solvent.ionic_strength,
        "ion_radius": solvent.ion_radius,
        "temperature": solvent.temperature,
        "surface_radius": solvent.surface_radius,
        "delphi": {
            "flavour": flavour.value,
            "prbrad": surface.probe_radius,
            "gaussian": surface.gaussian,
            "surfmethod": surface.keyword,
            "temper_written": round(temper, 6),
            "temper_units": "celsius" if flavour is DelphiFlavour.CPP else "kelvin",
            "bndcon": (_CPP_BOUNDARY_CODE if flavour is DelphiFlavour.CPP else _PY_BOUNDARY_NAME),
            "linit": options.linear_iterations,
            "maxc": options.max_delta_phi,
            **grid.as_diagnostics(),
        },
    }
