"""BoundaryElementRequest -> a TABI-PB input file.

Flat `key value` lines, and a short file, because a boundary-element solve has
far less to specify than a finite-difference one: no grid dimensions, no
centring, no focusing boundary, no charge discretization. What remains is the
structure, the dielectrics, the salt, and how finely to triangulate.

`mesh_density` on the request maps onto `sdens`, TABI-PB's vertices per square
angstrom of molecular surface. That parameter is the BEM analogue of grid
resolution, and it is the reason `BoundaryElementRequest` carries it while
`GridSpec` lives on the finite-difference request instead (ROADMAP.md section 2).
"""

from __future__ import annotations

from sashimi.protocol import Diagnostics, SolventModel
from sashimi.tabipb.options import TabipbOptions, resolve_mesh

__all__ = ["OUTPUT_PREFIX", "PQR_FILENAME", "build_input", "resolved_parameters"]

PQR_FILENAME = "mol.pqr"
OUTPUT_PREFIX = "solve"  # TABI-PB appends .vtk / .csv


def build_input(
    solvent: SolventModel,
    mesh_density: float,
    options: TabipbOptions = TabipbOptions(),  # noqa: B008 — frozen dataclass
    *,
    pqr_filename: str = PQR_FILENAME,
    output_prefix: str = OUTPUT_PREFIX,
    write_potential: bool = True,
) -> str:
    mesh = resolve_mesh(solvent.surface_model, options)

    lines = [
        "# Generated by sashimi. Do not edit; regenerate from the request.",
        f"mol               {pqr_filename}",
        f"mesh              {mesh}",
        f"sdens             {mesh_density:.6f}",
        f"srad              {solvent.surface_radius:.4f}",
        f"pdie              {solvent.solute_dielectric:.6f}",
        f"sdie              {solvent.solvent_dielectric:.6f}",
        f"bulk              {solvent.ionic_strength:.6f}",
        f"temp              {solvent.temperature:.4f}",
        f"tree_degree       {options.tree_degree}",
        f"tree_theta        {options.tree_theta:.4f}",
        f"tree_max_per_leaf {options.tree_max_per_leaf}",
        f"precondition      {'yes' if options.precondition else 'no'}",
        f"output_prefix     {output_prefix}",
    ]
    if write_potential:
        # The CSV is a single summary row; only the VTK carries the per-vertex
        # field that becomes a `SurfacePotential`.
        lines.append("outdata           vtk")

    return "\n".join(lines) + "\n"


def resolved_parameters(
    solvent: SolventModel, mesh_density: float, options: TabipbOptions
) -> Diagnostics:
    """What the backend actually used, for `Provenance.resolved_parameters`."""
    return {
        "surface_model": solvent.surface_model.value,
        "solvent_dielectric": solvent.solvent_dielectric,
        "solute_dielectric": solvent.solute_dielectric,
        "ionic_strength": solvent.ionic_strength,
        "temperature": solvent.temperature,
        "surface_radius": solvent.surface_radius,
        "tabipb": {
            "mesh": resolve_mesh(solvent.surface_model, options),
            "sdens": mesh_density,
            "srad": solvent.surface_radius,
            "tree_degree": options.tree_degree,
            "tree_theta": options.tree_theta,
            "tree_max_per_leaf": options.tree_max_per_leaf,
            "precondition": options.precondition,
        },
    }
